# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        MainWindow.setMinimumSize(QtCore.QSize(350, 350))
        MainWindow.setMaximumSize(QtCore.QSize(350, 350))
        MainWindow.setStyleSheet("background-color: rgb(125, 125, 125);\n"
"background-color: rgb(147, 147, 147);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Title = QtWidgets.QLabel(self.centralwidget)
        self.label_Title.setGeometry(QtCore.QRect(100, 20, 150, 20))
        self.label_Title.setMinimumSize(QtCore.QSize(150, 20))
        self.label_Title.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(14)
        self.label_Title.setFont(font)
        self.label_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Title.setObjectName("label_Title")
        self.label_Icon = QtWidgets.QLabel(self.centralwidget)
        self.label_Icon.setGeometry(QtCore.QRect(100, 50, 150, 150))
        self.label_Icon.setMinimumSize(QtCore.QSize(150, 150))
        self.label_Icon.setMaximumSize(QtCore.QSize(150, 150))
        self.label_Icon.setStyleSheet("image: url(:/RR/revolver.jpg);\n"
"background-color: rgb(255, 255, 255);")
        self.label_Icon.setText("")
        self.label_Icon.setObjectName("label_Icon")
        self.pushButton_Spin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Spin.setGeometry(QtCore.QRect(140, 225, 70, 25))
        self.pushButton_Spin.setMinimumSize(QtCore.QSize(70, 25))
        self.pushButton_Spin.setMaximumSize(QtCore.QSize(70, 25))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.pushButton_Spin.setFont(font)
        self.pushButton_Spin.setObjectName("pushButton_Spin")
        self.label_Result = QtWidgets.QLabel(self.centralwidget)
        self.label_Result.setGeometry(QtCore.QRect(145, 250, 60, 15))
        self.label_Result.setMinimumSize(QtCore.QSize(60, 15))
        self.label_Result.setMaximumSize(QtCore.QSize(60, 15))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.label_Result.setFont(font)
        self.label_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Result.setObjectName("label_Result")
        self.label_Bottom = QtWidgets.QLabel(self.centralwidget)
        self.label_Bottom.setGeometry(QtCore.QRect(25, 275, 300, 20))
        self.label_Bottom.setMinimumSize(QtCore.QSize(300, 20))
        self.label_Bottom.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.label_Bottom.setFont(font)
        self.label_Bottom.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Bottom.setObjectName("label_Bottom")
        self.pushButton_Again = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Again.setGeometry(QtCore.QRect(130, 205, 90, 25))
        self.pushButton_Again.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_Again.setMaximumSize(QtCore.QSize(90, 25))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(12)
        self.pushButton_Again.setFont(font)
        self.pushButton_Again.setObjectName("pushButton_Again")
        self.pushButton_Again.raise_()
        self.label_Title.raise_()
        self.label_Icon.raise_()
        self.pushButton_Spin.raise_()
        self.label_Result.raise_()
        self.label_Bottom.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Title.setText(_translate("MainWindow", "RUSSIAN ROULETTE"))
        self.pushButton_Spin.setText(_translate("MainWindow", "SPIN"))
        self.label_Result.setText(_translate("MainWindow", "You Live!"))
        self.label_Bottom.setText(_translate("MainWindow", "Would you like to play again?"))
        self.pushButton_Again.setText(_translate("MainWindow", "SPIN AGAIN"))
import resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
